//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_equipment { get; set; }
        public int ID_malfunction { get; set; }
        public int ID_client { get; set; }
        public string Job_description { get; set; }
        public int ID_satatus { get; set; }
        public int ID_executor { get; set; }
        public Nullable<int> time { get; set; }
        public int ID_priority { get; set; }
        public int ID_stage { get; set; }
        public string Comment { get; set; }
    
        public virtual malfunction malfunction { get; set; }
        public virtual priority priority { get; set; }
        public virtual stage stage { get; set; }
        public virtual status status { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
